{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "faf01fe6_f293a456",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 2974
      },
      "writtenOn": "2023-03-27T11:20:14Z",
      "side": 1,
      "message": "Minor issue with exception hierarchy, see comment inline.",
      "revId": "162b4038916e0e14fe766d3522a81c1d58a87903",
      "serverId": "e9e9afe9-4712-486d-8885-f54b72dd1951"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "8549e26b_ab5d728f",
        "filename": "java/src/test/java/org/wikimedia/metrics_platform/EndToEndIT.java",
        "patchSetId": 1
      },
      "lineNbr": 91,
      "author": {
        "id": 2974
      },
      "writtenOn": "2023-03-27T11:20:14Z",
      "side": 1,
      "message": "the `verify()` method above throws a `VerificationException` which does not extend `Exception`, but `Error`. So we should catch `VerificationException` directly, and the `await()` will do what you expect.",
      "range": {
        "startLine": 91,
        "startChar": 21,
        "endLine": 91,
        "endChar": 30
      },
      "revId": "162b4038916e0e14fe766d3522a81c1d58a87903",
      "serverId": "e9e9afe9-4712-486d-8885-f54b72dd1951"
    }
  ]
}